language: elixir
elixir:
  - '1.10.0'
otp_release:
  - '22.2'

jobs:
  include:
    - elixir: 1.9.0
      otp_release: '22.2'
    - elixir: 1.9.4
      otp_release: '22.2'
    - elixir: 1.10.0
      otp_release: '22.2'

script:
  - mix test